language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
env:
  - DJANGO=2.0
  - DJANGO=3.0
  - DJANGO=4.0
  - DJANGO=4.1
  - DJANGO=4.2
install:
  - pip install -r requirements.txt --use-mirrors
script:
  - python tests/manage.py test rated --settings=settings
