name: CI
on: [push, pull_request]

jobs:

  ci:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10, 3.11]
        django-version: [2.2, 3.2, 4.0, 4.1, 4.2]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: |
        pip install -e .
        pip install flake8 pytest
        pip install -U Django==${{ matrix.django-version }}
    - name: Lint
      run: flake8 rated/
    - name: Test
      run: pytest
